### ISSUE TITLE
How to use this code?

### ISSUE THREAD

**Issue by whatispwn** [armandochandi/V2X_MEC_5G#1]
Could you please tell me how to use these files?

**Comment by armandochandi** [comment]
Hello, in order to use this code I recommend you generate all the files indicated in the version of omnet that you are going to use and copy the text of each file, this way you will compile it in the environment, you can correct sentences in the process now Since there are changes in each version, be sure to import the library versions indicated. Successes

**Comment by whatispwn** [comment]
Well, thank you for your reply. I'll try my best to make full use of these files.
